---
fixtures:
  forge_modules:
    # Acceptance testing
    peadm: 'puppetlabs/peadm'
    apply_helpers: 'puppetlabs/apply_helpers'
    facts: 'puppetlabs/facts'
    ruby_task_helper: 'puppetlabs/ruby_task_helper'
    service: 'puppetlabs/service'
    stdlib: 'puppetlabs/stdlib'
    format: 'puppet/format'
    node_manager: 'WhatsARanjit/node_manager'

    # Debugging
    debug: 'nwops-debug'
  repositories:
    provision: 'https://github.com/puppetlabs/provision.git'
  symlinks:
    pbug: '#{source_dir}'
