---
fixtures:
  forge_modules:
    #    facts:
    #      repo: 'puppetlabs/facts'
    #      ref: '0.6.0'
    puppet_agent:
      repo: 'puppetlabs/puppet_agent'
      ref: '2.2.2'
  repositories:
    provision: 'https://github.com/puppetlabs/provision.git'
  symlinks:
    pbug: '#{source_dir}'
